<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">


    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('codeConductor') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                              <li class="active"><a href="<?php echo $this->url('blog') ?>"><?php echo $this->translate('Blog') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
                <a href="<?php echo $this->url("logout");  ?>"><?php echo $this->translate("Log Out"); ?></a>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <div class="dashnav">
            <h3>Admin Nav </h3>
              <li class="active"><a href="<?php echo $this->url('viewposts') ?>"><?php echo $this->translate('Posts') ?></a></li>      
           
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>