<?php
// module/Album/view/album/album/index.phtml:

$title = 'My posts';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($posts as $post) : ?>
<tr>
    <td><?php echo "<a href='blog/{$this->escapeHtml($post->post_name)}'>". $this->escapeHtml($post->post_title)."</a>";?></td>
    <td><?php echo $this->escapeHtml($post->post_content);?></td>

</tr>
<?php endforeach; ?>
</table>