<?php
// module/Album/view/album/album/index.phtml:

$title = 'My posts';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<a href="<?php echo $this->url('addpost'); ?>">Add Post</a>
<table class="table">
<tr>
    <th>Title</th>
    <th>Author</th>
    <th>Category</th>
    <th>Status</th>
    <th>Date</th>
</tr>
<?php foreach ($posts as $post) : 
    $dateparts = explode(" ", $post->date);
    $date = $dateparts[0];
 ?>

<tr>
    <td><?php echo "<a href='edit-post/{$this->escapeHtml($post->ID)}'>". $this->escapeHtml($post->post_title)."</a>";?></td>
    <td><?php echo $this->escapeHtml($post->post_author);?></td>
    <td><?php echo $this->escapeHtml($post->post_category);?></td>
    <td><?php echo $this->escapeHtml($post->post_status);?></td>
    <td><?php echo $date;?></td>
</tr>
<?php 

endforeach; ?>
</table>