<?php
// module/Album/view/album/album/index.phtml:

$title = 'Single Post';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><?php echo $post->post_content; ?></p>


<h2>Comments</h2>


<ul>
<?php  foreach($comments as $comment) : ?>
    
    <li> <?= $comment->comment_content;?></li>
    
<?php endforeach; ?>
</ul>
<?php
$form ->setAttribute('action', "/blog/$name");
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>